name: sum
description: Useful Sum types/Unions expressed in Dart for asynchronous data, error handling, and more!
version: 0.2.0
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/purplenoodlesoop/sum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
   meta: ^1.7.0

dev_dependencies:
  purple_lints: ^0.2.0
  test: ^1.16.0
